### ISSUE TITLE
Cannot install on Windows ..

### ISSUE THREAD

**Issue by ArunNairID** [reiinakano/xcessiv#5]
Environment = Anaconda Python 3.6

Os= Windows 10

`Collecting xcessiv
  Using cached xcessiv-0.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Arun\AppData\Local\Temp\pip-build-enuakn0v\xcessiv\setup.py", line 8, in <module>
        import xcessiv
      File "C:\Users\Arun\AppData\Local\Temp\pip-build-enuakn0v\xcessiv\xcessiv\__init__.py", line 12, in <module>
        import xcessiv.views
      File "C:\Users\Arun\AppData\Local\Temp\pip-build-enuakn0v\xcessiv\xcessiv\views.py", line 5, in <module>
        from rq import Connection
      File "C:\Anaconda3\envs\python36\lib\site-packages\rq\__init__.py", line 11, in <module>
        from .worker import SimpleWorker, Worker
      File "C:\Anaconda3\envs\python36\lib\site-packages\rq\worker.py", line 88, in <module>
        class Worker(object):
      File "C:\Anaconda3\envs\python36\lib\site-packages\rq\worker.py", line 361, in Worker
        def kill_horse(self, sig=signal.SIGKILL):
    AttributeError: module 'signal' has no attribute 'SIGKILL'
`

**Comment by reiinakano** [comment]
Hi, unfortunately, Xcessiv does not currently support Windows as it uses RQ as its job queue.

I can't really give a timeline as to when I'll decide to support Windows as that would require rewriting to use Celery instead of RQ, and I think there are quite a lot more pressing issues I'd like to focus on at the moment. But this issue is noted and if demand for Windows support is indeed big enough, I'll consider moving it up.

**Comment by reiinakano** [comment]
For everyone using Windows, as of v0.2.1, Xcessiv now provides an experimental Docker image. Please visit the documentation for usage.

**Comment by ArunNairID** [comment]
@reiinakano, I was able to utilise Windows Linux Subsystem to run it. Wrote a tutorial running Python apps on WSL. The Ubuntu on Windows is sufficient to run the software.

**Comment by reiinakano** [comment]
@ArunNairID That sounds awesome! Could you link it? I'd like to refer to it in the official docs for running on Windows as an alternative to Docker.

**Comment by ArunNairID** [comment]
@reiinakano  Please find the link for configuring the Windows machine with Ubuntu WSL. https://medium.com/xtrememl/why-how-to-use-windows-10-wsl-built-in-linux-for-machine-learning-6a225f4bbd3a
