### ISSUE TITLE
Error with tuple hyperparameters

### ISSUE THREAD

**Issue by psardin** [reiinakano/xcessiv#57]
Hello @reiinakano 

I have an issue with tuple hyperparameters. I think the bracket are ommited during the training

`from gplearn.genetic import SymbolicRegressor
base_learner = SymbolicRegressor(random_state=8,n_jobs=6)`

`params = {'function_set':('sqrt','add', 'sub', 'mul', 'div','max','min','log'),
'const_range':(-30, 280),
'init_depth':(6, 13)
'population_size': 150, 
'generations': 600, 
'stopping_criteria': 0.001,
'p_crossover': 0.45, 
'p_subtree_mutation': 0.15,
'p_hoist_mutation': 0.15, 
'p_point_mutation': 0.25, 
'max_samples': 0.85, 
'metric': 'rmse',
'parsimony_coefficient': 0.0002}`

`Traceback (most recent call last):
File "/root/anaconda3/lib/python3.6/site-packages/xcessiv/rqtasks.py", line 135, in generate_meta_features
est = est.fit(X_train, y_train)
File "/root/anaconda3/lib/python3.6/site-packages/gplearn/genetic.py", line 366, in fit
raise ValueError('const_range should be a tuple with length two.')
ValueError: const_range should be a tuple with length two.`

**Comment by reiinakano** [comment]
I have reproduced this error. Unfortunately, I currently do not have the time to look too deep into what is causing this. May I ask why you're trying to use `xcessiv` with `gplearn`? It seems like it would take up too much time as each `gplearn` estimator is doing its own optimization inside.

**Comment by psardin** [comment]
Im using gplearn as a base learner to add less correlated model to my ensemble (kaggle competition)
